### ISSUE TITLE
Scrolling up and down while playing

### ISSUE THREAD

**Issue by Murat-Karakaya** [ekinkaradag/snake-vue3#15]
**problem**
I love this repository and it is very good. But there is a problem:
While playing this game when I press down arrow, snake goes down. and when I press up arrow,  the snake goes up. There is no problem in that. But the website itself also scroll when pressed upp and down arrows. Wich results in a bit annoying problem where the page scrolling up and down while I just want to play a game.

**solution**
I think instead of playing the game directly on the website, playing the game inside a modal would be a better idea. But it won't be so easy coding all that

**Describe alternatives you've considered**
Maybe using w, a, s, d keys instead of arrow keys would be a fast solution. But while w, a, s, d keys are aligned all nice and simple in
Q keyboard ; it is not aligned very nice in the F keyboard. Making this game pretty much unplayable in F keyboard.

Maybe decreasing the height of the website is a simple, fast, easy solution. Afterall, if the height of the website is small enaugh, then there won't be a scrolling bar and no annoying scrolling problem

**Comment by ekinkaradag** [comment]
Thank you very much @Murat-Karakaya for taking the time and meticulously creating this issue. The issue was resolved by applying this logic:

1. Listen to `keydown` events.
2. If a direction key was pressed, prevent default browser behavior and carry on with the task of changing directions accordingly.
3. If any other key was pressed, do **not** prevent the default browser behavior.

**Comment by ekinkaradag** [comment]
The fix is applied in [`version 0.1.3`](https://github.com/ekinkaradag/snake-vue3/releases/tag/0.1.3_beta).

**Comment by Murat-Karakaya** [comment]
Yep, the new version is very great. Keep the good work 👍
